---
- name: "Template PVC"
  template:
    src: CreatePersistentVolume.j2
    dest: CreatePersistentVolume.yml

- name: "Criando PVC: {{item.deploy_name}}"
  k8s:
    state: present
    definition: "{{ lookup('file', 'CreatePersistentVolumeClaim.yml') | from_yaml }}"
