---
- name: "Get deployment: {{ item.deploy_name }}"
  command: "kubectl get deployments/{{ item.deploy_name }} -o json -n {{ item.namespace }}"
  register: dc_app

#- name: "Get deployment - Helm: {{item.deploy_name}}-{{ item.deploy_name }}"
#  command: "kubectl get deployments/{{ item.deploy_name }}-{{ item.deploy_name }} -o json -n {{ item.namespace }}"
#  register: dc_app
#  when: ('helm' in item.keys()) and (item.helm)

- name: "Template service"
  template:
    src: Service.j2
    dest: Service.yml
  when: (item.deploy_name in dc_app.stdout|from_json|json_query('metadata.labels.app'))

- name: "Create service: {{item.deploy_name}}"
  k8s:
    state: present
    definition: "{{ lookup('file', 'Service.yml') | from_yaml }}"
  when: (item.routes is defined) and (item.routes) and (item.deploy_name in dc_app.stdout|from_json|json_query('metadata.labels.app')) and ('helm' not in item.keys())

