---
- name: "Get ingresses: {{ item.namespace }}"
  command: "kubectl get ing -o json -n {{ item.namespace }}"
  register: route

- name: "Get a list with all services: {{ item.namespace }}"
  k8s_facts:
    api_key: "{{ token }}"
    api_version: v1
    kind: Service
    namespace: "{{ item.namespace }}"
  register: svc_list

- name: "Select specific SVC {{ item.group }}/{{ item.deploy_name }}"
  k8s_route:
    services: "{{ svc_list }}"
    appname: "{{ item.deploy_name }}"
  register: specific_svc

- name: "Check if ports are exposed"
  fail:
    msg: "Porta {{ routes.port }} nao exposta!!!"
  when: "(routes.port|int not in specific_svc.result|json_query('spec.ports[*].port') and item.deploy_name not in dc_app.stdout|from_json|json_query('metadata.labels.app'))"
  with_items: "{{ item.routes }}"
  loop_control:
    loop_var: routes

- name: "Template route: {{ routes.name }}"
  template:
    src: CreateIngress.j2
    dest: CreateIngress.j2
  when: (item.deploy_name in dc_app.stdout|from_json|json_query('metadata.labels.app') and routes.name not in route.stdout|from_json|json_query('items[*].metadata.name'))
  with_items: "{{ item.routes }}"
  loop_control:
    loop_var: routes

- name: "Create route: {{ routes.name }}"
  k8s:
    state: present
    definition: "{{ lookup('file', 'CreateIngress.j2') | from_yaml }}"
  when: (item.deploy_name in dc_app.stdout|from_json|json_query('metadata.labels.app') and routes.name not in route.stdout|from_json|json_query('items[*].metadata.name'))
  with_items: "{{ item.routes }}"
  loop_control:
    loop_var: routes
