---
- name: "Capturando Ingress: {{ item.namespace }}"
  shell: "kubectl get ing -o json -n {{ item.namespace }}"
  register: ingresses

- name: "Capturando a uma lista com todos os serviços no:  {{ item.namespace }}"
  k8s_facts:
    api_version: v1
    kind: Service
    namespace: "{{ item.namespace }}"
  register: svc_list

- name: "Selecionando SVC especifico: {{ item.namespace }}/{{ item.deploy_name }}"
  k8s_facts:
    api_version: v1
    kind: Service
    namespace: "{{ item.namespace }}"
  register: specific_svc

- name: "Debug srv variable"
  debug:
    var: specific_svc

- name: "Verificando portas expostas"
  fail:
    msg: "Porta {{ route.port }} nao exposta!!!"
  when: "(routes.port|int not in specific_svc.result|json_query('spec.ports[*].port'))"
  with_items: "{{ item.routes }}"
  loop_control:
    loop_var: routes

