---
- hosts: "{{ target }}"
  
  vars:
      cpu:
        min: "100"
        max: "200"
      memory:
        min: "100"
        max: "256"

  vars_files:
    - "{{ deploy_vars }}"

  tasks:
    - name: "Criando namespace"
      include_role:
        name: kubernetes_create_namespace
    
