---
- name: "Check if namespace {{ item.namespace }} exists"
  command: "kubectl get --no-headers=true namespaces -o custom-columns=:metadata.name"
  register: namespace_list

- name: "Create namespace: {{ item.namespace }}"
  command: "kubectl create namespace {{ item.namespace }}"
  when: "(item.namespace not in namespace_list.stdout_lines|list)"

- name: "Apply patch node-selector: {{ item.group }}"
  command: "kubectl patch namespace {{ item.namespace }} --patch '{\"metadata\": {\"annotations\": {\"kubernetes.io/node-selector\": \"region={{ region|lower }}\"}}}'"
  when: "(item.namespace not in namespace_list.stdout_lines|list) and (region) and ((region|lower == 'prd') or (region|lower == 'dev'))"
