---
- name: "Capturando DC: {{ item.namespace }}/{{ item.deploy_name }}"
  shell: "kubectl get deploy -o json -n {{ item.namespace }}"
  register: dc_global

- name: "Atualizando imagem no deployment: {{ item.namespace}}/{{ item.deploy_name }}"
  shell: "kubectl set image deploymeny/{{ item.deploy_name }} {{ item.deploy_name }}={{ item.image }}"
  when: (item.deploy_name in dc_global.stdout|from_json|json_query('items[*].metadata.labels.app'))
