---
- hosts: "{{ target }}"

  vars:
    cpu:
      min: "100"
      max: "200"
    memory:
      min: "100"
      max: "256"

  vars_files:
    - "{{ deploy_vars }}"

  tasks:
    - name: "Login into docker registry"
      include_role:
        name: kubernetes_login
      when: docker_registry is defined

    - name: "Create project"
      include_role:
        name: kubernetes_create_namespace
      with_items: "{{ apps }}"
      vars:
        included_variable: "{{ item }}"

    - name: "Create app"
      include_role:
        name: kubernetes_create_app
      with_items: "{{ apps }}"
      vars:
        included_variable: "{{ item }}"

    - name: "Create service"
      include_role:
        name: kubernetes_create_srv
      with_items: "{{ apps }}"
      vars:
        included_variable: "{{ item }}"
      when: ('helm' not in item.keys())

    - name: "Create route"
      include_role:
        name: kubernetes_create_route
      with_items: "{{ apps }}"
      vars:
        included_variable: "{{ item }}"

    - name: "Updating variables"
      include_role:
        name: kubernetes_update_vars
      with_items: "{{ apps }}"
      when: "not((item.env_vars is undefined) or (item.env_vars is none) or (item.env_vars|trim == ''))  and ('helm' not in item.keys()) and not(item.helm)"
      vars:
        included_variable: "{{ item }}"

    - name: "Applying changes"
      include_role:
        name: kubernetes_rollout
      with_items: "{{ apps }}"
      vars:
        included_variable: "{{ item }}"
